﻿server:
  port: 16089
  context-path: /
spring:
  application:
    name: boot-sharding-jpa
  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
sharding:
  jdbc:
    datasource:
      names: test
      test:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user:
            #主键
            key-generator-column-name: id
            #数据节点,均匀分布
            actual-data-nodes: test.t_user${0..1}
            #分表策略
            table-strategy:
              #行表达式
              inline:
                sharding-column: id
                #按模运算分配
                algorithm-expression: test.t_user${id % 2}