server:
  port: 16002
  context-path: /

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      defaultZone: http://localhost:16000/eureka/

spring:
  application:
    name: BOOT-RABBITMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: spring
    password: 123456
    virtual-host: /
    publisher-confirms: true
