server:
  port: 16076
  context-path: /
spring:
  application:
    name: boot-mybatis
  datasource:
    url: jdbc:mysql://localhost:3306/simple_dev?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      validation-query: SELECT 1
      test-while-idle: true
#mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.yq.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  enum-as-simple-type: true
  not-empty: true

