﻿server:
  port: 16073
  context-path: /
spring:
  application:
    name: boot-kafka
kafka:
  brokers: 192.168.101.3:9092
  topic:
    consumer: test
    singleConsumerGroupId: SingleConsumer
    multiConsumerGroupId: MultiConsumer
    producer: test