﻿server:
  port: 16073
  context-path: /
spring:
  application:
    name: boot-kafka
kafka:
  brokers: 192.168.101.168:9092
  topic:
    consumer: user-t
    singleConsumerGroupId: SingleConsumer
    multiConsumerGroupId: MultiConsumer
    producer: user-t